version: '3'

services:
  railsapi:
    build: ./backend
    # left is host machine port : docker image port
    ports:
      - "8000:3090"
    volumes:
      - ./backend:/usr/src/app
    env_file:
      - .env/development/database
      - .env/development/railsapi
    depends_on: 
      - database 

  database:
    image: postgres
    env_file:
      - .env/development/database
    volumes: 
      - db_data:/var/lib/postgresql/data

  frontend:
    build: ./frontend
    environment: 
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=10000
    ports:
      - "3000:3000"
    depends_on: 
      - railsapi
    #volumes:
      #- ./frontend:/usr/src/app
      #- /usr/src/app/node_modules
    # https://stackoverflow.com/questions/51097652/install-node-modules-inside-docker-container-and-synchronize-them-with-host
    # Always use docker-compose up --build whenever there is a change
    # After git pull, if docker is running, stop docker and up it again with same command
    command: /usr/src/app/entrypoint.sh

volumes:
  db_data: