version: '3'

services:
  railsapi:
    build: ./backend
    # left is host machine port : docker image port
    ports:
      - "8000:3090"
    volumes:
      - ./backend:/usr/src/app
    env_file:
      - .env/development/database
      - .env/development/railsapi
    depends_on: 
      - database 

  database:
    image: postgres
    env_file:
      - .env/development/database
    volumes: 
      - db_data:/var/lib/postgresql/data

  frontend:
    build: ./frontend
    environment: 
      CHOKIDAR_USEPOLLING: "true"
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app
    depends_on: 
      - railsapi

volumes:
  db_data: